version: "3.9"

services:
  api:
    profiles: [ "api" ]
    container_name: user_service.api
    build:
      context: .
    restart: unless-stopped
    expose:
      - "5000"
    ports:
      - "5000:5000"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - user_service.postgres.network
      - user_service.rabbitmq.network
    volumes:
      - ./config:/app/config:ro
    environment:
      - CONFIG_PATH=${CONFIG_PATH:-./config/prod_config.toml}
    command: ["python", "-Om", "src"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsSL http://localhost:5000/healthcheck/"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  postgres_migration:
    profiles: [ "migration" ]
    container_name: user_service.postgres_migration
    build:
      context: .
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - user_service.postgres.network
    volumes:
      - ./config:/app/config:ro
      - ./alembic.ini:/app/alembic.ini:ro
      - ./src/infrastructure/db/migrations:/app/src/infrastructure/db/migrations:ro
    environment:
      - CONFIG_PATH=${CONFIG_PATH:-./config/prod_config.toml}
    command: ["python", "-m", "alembic", "upgrade", "head"]

  postgres:
    profiles: [ "api", "migration" ]
    container_name: user_service.postgres
    image: "postgres:15-alpine"
    hostname: user_service.postgres
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "0.0.0.0:15432:5432"
    networks:
      - user_service.postgres.network
    environment:
      POSTGRES_PASSWORD: 2685118
      POSTGRES_USER: postgres
      POSTGRES_DB: user_service
    volumes:
      - user_service.postgres.data:/var/lib/postgresql/users:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  postgres_backup:
    profiles: [ "api" ]
    container_name: user_service.postgres_backup
    image: prodrigestivill/postgres-backup-local:15-alpine
    networks:
      - user_service.postgres.network
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=user_service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2685118
      - BACKUP_DIR=/backups
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=${POSTGRES_BACKUP_SCHEDULE:-@daily}
      - HEALTHCHECK_PORT=8080
    volumes:
      - ${POSTGRES_BACKUP_DIR:-./.backups/postgres}:/backups

  rabbitmq:
    profiles: [ "api" ]
    image: rabbitmq:3.11-management-alpine
    container_name: user_service.rabbitmq
    hostname: user_service.rabbitmq
    restart: unless-stopped
    expose:
      # AMQP protocol port
      - "5672"
      # HTTP management UI
      - "15672"
    ports:
      - "0.0.0.0:5672:5672"
      - "0.0.0.0:15672:15672"
    networks:
      - user_service.rabbitmq.network
    volumes:
      - user_service.rabbitmq.data:/var/lib/rabbitmq/:rw
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-admin}
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics check_running -q"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

volumes:
  user_service.postgres.data: {}
  user_service.rabbitmq.data: {}

networks:
  user_service.postgres.network: {}
  user_service.rabbitmq.network: {}